from enum import Enum

LISTENING = 10
MAX_TRANSMISSION_DELAY = 5
MAX_PROCESSING_DELAY = 2
TOTAL_DELAY = (2 * MAX_TRANSMISSION_DELAY) + MAX_PROCESSING_DELAY
HEARTBEAT_TIME = 5
BUFF_SIZE = 1024
DEFAULT_ID = -1

class Type(Enum):
    ELECTION = 0
    END = 1
    HEARTBEAT = 3
    SUBSCRIBE = 6
    ANSWER = 2
    REGISTER = 4
    ACK = 5